### ISSUE TITLE
revisit GET_LIST_READY_ENTITIES

### ISSUE THREAD

**Issue by dirk-thomas** [ros2/rclpy#201] opened 2018-06-28 22:05 UTC
Follow up of #197.

When `PyLong_FromUnsignedLongLong` return `NULL` it should be reported somehow. If `NULL` is returned it needs to be ensured that it is handled correctly by all callers. Also the return value of `PyList_Append` should be checked.

**Comment by sloretz** [comment] 2018-07-02 15:15
Partial duplicate of #139 ?

**Comment by mikaelarguedas** [comment] 2018-07-05 17:25
closing as duplicate of #139

**Closed by mikaelarguedas** 2018-07-05 17:25 UTC
Labels: bug
